# Generated by Django 2.1.5 on 2020-02-28 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setsanitaryTemp', models.CharField(max_length=2, null=True)),
                ('sethotwaterTemp', models.CharField(max_length=2, null=True)),
                ('actualsanitaryTemp', models.CharField(max_length=2, null=True)),
                ('actualhotwaterTemp', models.CharField(max_length=2, null=True)),
                ('timer', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('batterystatus', models.CharField(max_length=200, null=True)),
                ('batterylevel', models.CharField(max_length=200, null=True)),
                ('heaters', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
