# Generated by Django 2.1.5 on 2020-02-28 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='actualhotwaterTemp',
            field=models.CharField(default='0000005', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='actualsanitaryTemp',
            field=models.CharField(default='0000003', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='batterylevel',
            field=models.CharField(default='0000009', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='batterystatus',
            field=models.CharField(default='0000008', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='heaters',
            field=models.CharField(default='00000010', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sethotwaterTemp',
            field=models.CharField(default='0000002', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='setsanitaryTemp',
            field=models.CharField(default='0000001', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default='0000007', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timer',
            field=models.CharField(default='0000006', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
