# Generated by Django 2.1.5 on 2020-02-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200228_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='actualhotwaterTemp',
            field=models.CharField(default='5', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='actualsanitaryTemp',
            field=models.CharField(default='3', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='batterylevel',
            field=models.CharField(default='9', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='batterystatus',
            field=models.CharField(default='8', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='heaters',
            field=models.CharField(default='10', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sethotwaterTemp',
            field=models.CharField(default='2', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='setsanitaryTemp',
            field=models.CharField(default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default='7', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timer',
            field=models.CharField(default='6', max_length=200, null=True),
        ),
    ]
