# Generated by Django 2.1.5 on 2020-02-29 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
