# Generated by Django 2.2.11 on 2020-03-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='actualhotwaterTemp',
            field=models.CharField(default='4', max_length=2, null=True),
        ),
    ]
