# Generated by Django 2.2.11 on 2020-03-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200319_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='hotwaterstatus',
        ),
        migrations.AddField(
            model_name='profile',
            name='sanitarystatus',
            field=models.CharField(default='7', max_length=200, null=True),
        ),
    ]
