# Generated by Django 2.2.11 on 2020-03-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200324_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hotwaterstatus',
            field=models.CharField(default='55', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sanitarystatus',
            field=models.CharField(default='66', max_length=200, null=True),
        ),
    ]
