# Generated by Django 2.2.11 on 2020-03-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200324_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='timer',
            new_name='timer1',
        ),
        migrations.AddField(
            model_name='profile',
            name='timer2',
            field=models.CharField(default='6', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timer3',
            field=models.CharField(default='6', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timer4',
            field=models.CharField(default='6', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timer5',
            field=models.CharField(default='6', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timer6',
            field=models.CharField(default='6', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timer7',
            field=models.CharField(default='6', max_length=200, null=True),
        ),
    ]
